### ISSUE TITLE
Didn't fix the freezing issues I was having in Speedy Blupi I (when music track switches)

### ISSUE THREAD

**Issue by NonlinearFruit** [Schatteneis/speedy-blupi-music-fix#1]
- I downloaded the files from the latest commit
- I replaced the files by the same name in `C:/Speedy Blupi/Sound`
- Opening Speedy Blupi still results in freezing when sound track changes

Did I do something wrong? Any recommendations on how to fix?

**Comment by Schatteneis** [comment]
sorry this took so long, updating the files right now

**Comment by Schatteneis** [comment]
updated the files, should work now

**Comment by Schatteneis** [comment]
after some more investigation by someone from the reverse engineering team it might be that the game force reloads the MultiMedia dll, thats why the game freezes
